---
title: 'Test'
---

# Readings

## Textbooks

```{r}
librarian::shelf(
  glue, RefManageR)
bib <- ReadBib("ml-env.bib", check = FALSE)
BibOptions(check.entries = FALSE, style = "markdown", cite.style = "authoryear", bib.style = "authoryear")
```

The following textbooks are used in the course with these acronyms in the Course Schedule:

```{r, print_refs, results='asis', echo=FALSE, warning=FALSE, message=FALSE}

bib_txt <- function(acronym, link, bibkey){
  writeLines(glue("- [_{acronym}_]({link}) "))
  print(
    bib[key = bibkey], 
    .opts = list(
      check.entries = FALSE, 
      style = "html", 
      bib.style = "authoryear"))
}
bib_txt(
  "SDMR", "https://rspatial.org/raster/sdm/",
  "hijmansSpeciesDistributionModeling2021")
bib_txt(
  "HOMLR", "https://bradleyboehmke.github.io/HOML/",
  "greenwellHandsOnMachineLearning2020")
bib_txt(
  "DLR", "https://drive.google.com/open?id=16Tr0IYufMnTqszkyzXzRM0XmQDjWuwXv&authuser=ben%40ecoquants.com&usp=drive_fs",
  "cholletDeepLearning2018")
bib_txt(
  "DLPy", "https://drive.google.com/open?id=16TxVeHT_7ktz6Oh7xcZ3uMzxHaNQ16Dc&authuser=ben%40ecoquants.com&usp=drive_fs",
  "cholletDeepLearningPython2018")
```

## Articles

```{r references, results = "asis", echo = FALSE}
NoCite(bib, "zhongMachineLearningNew2021")
NoCite(bib, "elithSpeciesDistributionModels2009")
NoCite(bib, "evansModelingSpeciesDistribution2011")
NoCite(bib, "andradeENMTMLPackageStraightforward2020")
NoCite(bib, "kindtTreeDiversityAnalysis2005")

PrintBibliography(bib, .opts = list(check.entries = FALSE, sorting = "ynt"))
```
